import os
import sqlite3
from datetime import datetime

# Define database location relative to this file
DB_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(DB_DIR, "investigations.db")

def init_db():
    """Initializes the SQLite database and creates the cached_intel table if it doesn't exist."""
    os.makedirs(DB_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS cached_intel (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ioc TEXT UNIQUE,
                ioc_type TEXT,
                api_risk_score TEXT,
                llm_verdict TEXT,
                timestamp DATETIME
            )
            """
        )
        conn.commit()
    finally:
        conn.close()

def get_cached(ioc):
    """Retrieves cached intelligence for a given IOC.
    
    Args:
        ioc (str): The Indicator of Compromise to look up.
        
    Returns:
        dict or None: A dictionary containing the cached intel or None if not found.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    try:
        cursor.execute(
            "SELECT id, ioc, ioc_type, api_risk_score, llm_verdict, timestamp FROM cached_intel WHERE ioc = ?",
            (ioc,)
        )
        row = cursor.fetchone()
        if row:
            return dict(row)
        return None
    finally:
        conn.close()

def save_cached(ioc, ioc_type, api_risk_score, llm_verdict):
    """Saves or updates cached intelligence for a given IOC.
    
    Args:
        ioc (str): The Indicator of Compromise.
        ioc_type (str): The type of IOC (e.g., 'ip', 'domain', 'hash').
        api_risk_score (str): Risk score from threat intel APIs.
        llm_verdict (str): Analysis verdict generated by the LLM.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    try:
        cursor.execute(
            """
            INSERT INTO cached_intel (ioc, ioc_type, api_risk_score, llm_verdict, timestamp)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(ioc) DO UPDATE SET
                ioc_type = excluded.ioc_type,
                api_risk_score = excluded.api_risk_score,
                llm_verdict = excluded.llm_verdict,
                timestamp = excluded.timestamp
            """,
            (ioc, ioc_type, api_risk_score, llm_verdict, now)
        )
        conn.commit()
    finally:
        conn.close()

if __name__ == "__main__":
    init_db()
    print(f"Database initialized successfully at: {DB_PATH}")
